Small update

diff --git a/bin/getkvsecret b/bin/getkvsecret
--- a/bin/getkvsecret
+++ b/bin/getkvsecret
@@ -9,7 +9,8 @@ COMMANDS="az basename"
 
 for COMMAND in $COMMANDS; do
   if [ ! $(command -v $COMMAND) ]; then
-    fail "Could not find '$COMMAND' command. Is it installed?"
+    echo "Could not find '$COMMAND' command. Is it installed?"
+    exit 2
   fi
 done
 
@@ -49,17 +50,20 @@ set_variable()
 while getopts 'k:s:?h' o
 do
   case $o in
-    k) set_variable KEYVAULT $OPTARG ;;
-    s) set_variable SECRET $OPTARG ;;
+    k) LOCALKEYVAULT=$OPTARG ;;
+    s) LOCALSECRET=$OPTARG ;;
     h|?) usage ;;
   esac
 done
+
+KEYVAULT=${KEYVAULT:-$LOCALKEYVAULT}
+SECRET=${SECRET:-$LOCALSECRET}
 
 if [ -z "$SECRET" ]; then
   SECRET=$BASENAME
 fi
 
-if [ "$SECRET" == "getkvsecret" ]; then
+if [ "$SECRET" = "getkvsecret" ]; then
   usage
 fi
 
